apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: e2e-tests-nodejs-qembxlpd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-nodejs-qembxlpd 
  name: e2e-tests-nodejs-qembxlpd
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: e2e-tests-nodejs-qembxlpd
    weight: 100 
